global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "project1"
    static_configs:
      - targets: ["project1:8001"]  # si Project 1 expose /metrics
    
  - job_name: "project2"
    static_configs:
      - targets: ["project2:8002"]  # si Project 2 expose /metrics
