name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-projects:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [project-1, project-2, project-3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies for ${{ matrix.project }}
        run: |
          cd ${{ matrix.project }}
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          cd ${{ matrix.project }}
          flake8 .

      - name: Run tests with pytest
        run: |
          cd ${{ matrix.project }}
          if [ -d tests ]; then pytest; else echo "No tests directory"; fi