name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-template:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [project-1, project-2, project-3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies for ${{ matrix.project }}
        run: |
          cd ${{ matrix.project }}
          pip install -r requirements.txt

      - name: Run minimal tests
        run: |
          PYTHONPATH=${{ matrix.project }} pytest ${{ matrix.project }}/tests